name: Build and test
on:
  push:

permissions:
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up JDKs
        uses: actions/setup-java@v5
        with:
          # last one is default version
          java-version: |
            17
            21
            25
            8
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Build with Gradle
        run: ./gradlew assemble --continue --full-stacktrace
      - name: Test with Gradle
        run: ./gradlew check --continue --full-stacktrace
      - name: Save ktlint reports
        uses: jwgmeligmeyling/checkstyle-github-action@v1
        if: always() # always run even if the previous step fails
        with:
          name: ktlint
          title: ktlint Code Analyzer Report
          path: '**/ktlint*.xml'
      - name: Save detekt reports
        uses: jwgmeligmeyling/checkstyle-github-action@v1
        if: always() # always run even if the previous step fails
        with:
          name: detekt
          title: detekt Code Analyzer Report
          path: '**/detekt.xml'
      - name: Publish JUnit Test Report
        uses: mikepenz/action-junit-report@v6
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test*/TEST-*.xml'
